---
title: '0.1_sparseSTATIS'
author: "Ju-Chi.Yu"
date: "3/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# detach("package:SPAFAC", unload = TRUE)
# devtools::install_github("juchiyu/SPAFAC")

library(MExPosition)
library(PTCA4CATA)
library(ggplot2)
library(ggrepel)
library(tidyverse)
library(plotly)
library(RColorBrewer)
library(kableExtra)
library(ggpubr)
library(ggplotify)
library(SPAFAC)
library(sGSVD)
library(inlmisc)
library(pheatmap)
# devtools:install_github("jokergoo/ComplexHeatmap")
# library(ComplexHeatmap)

load("../01_data/MFA_turkeysensory.rda")

source("../02_analysis_sparseDiSTATIS//functions/PlotFactor.R")
source("../02_analysis_sparseDiSTATIS//functions/createxyLabels.gen.digit.R")
source("../02_analysis_sparseDiSTATIS//functions/createLabel.gen.digit.R")
source("../02_analysis_sparseDiSTATIS//functions/plot.smca.results.R")
source("../02_analysis_sparseDiSTATIS//functions/PlotMyScree.R")

# other functions
extract_si <- function(sdisca, si = "SI", fromSGSVD = FALSE) {
  if ("list" %in% class(sdisca)) {
    if (fromSGSVD) {
      return(sdisca$SI[[si]])
    }else {
      return(sdisca$sparsity$SI[[si]])
    }
  } else if (is.na(sdisca)) {
    return(NA)
  } else {
    stop("Something is a foot!")
  }
}

pivot_the_tab <- function(dat) {
  df <- data.frame(V = unname(t(data.frame(dat))))
  df %>% 
    tidyr::pivot_longer(starts_with("V"), names_to = "k", names_prefix = "V\\.") %>%
    select(value) %>% purrr::as_vector() %>% unname()
}

rownames(grand.tab) <- gsub("PECHUGA DE PAVO ", "", rownames(grand.tab))
rownames(grand.tab) <- c("HORNEADO", "SABORI", "DE FUD", "CAMPESTRE", "VIRGINIA", "NATURAL", "CLÃSICA", "ALPINO")

## design by raters
raters <- sapply(strsplit(colnames(grand.tab), "\\."), "[", 2)
raters.coldx <- data.frame(t(raters))
colnames(raters.coldx) <- colnames(grand.tab)

raters.fac <- factor(raters, levels = unique(raters))

## design by flavor
flavors <- sapply(strsplit(colnames(grand.tab), "\\."), "[", 1)
flavors.coldx <- data.frame(t(flavors))
colnames(flavors.coldx) <- colnames(grand.tab)

## design by flavor when grand.tab is ordered by flavors
flavors.ord <- rep(unique(flavors), each = 8)
flavors.ord.coldx <- data.frame(t(flavors.ord))

## get color ------------------
col.raters <- list()
col.raters$gc <- c('#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#E8C245','#a65628','#f781bf') %>% as.matrix
col.raters$oc <- rep(col.raters$gc, each = 12) %>% as.matrix
rownames(col.raters$gc) <- unique(raters)
rownames(col.raters$oc) <- colnames(grand.tab)

## when the columns are ordered by flavors (instead of raters)
col.flavor.idx <- c("#4e79a7", "#f28e2b", "#e15759", "#76b7b2", "#59a14f", "#edc948", "#b07aa1", "#ff9da7", "#9c755f", "#bab0ac", "#c3bc3f", "#8cc2ca")
names(col.flavor.idx) <- unique(flavors)
col.flavors <- list()
col.flavors$gc <- col.flavor.idx %>% as.matrix()
col.flavors$oc <- recode(flavors, !!!col.flavor.idx) %>% as.matrix()
rownames(col.flavors$oc) <- colnames(grand.tab)


## get theme -----------------
ggtheme <- theme(axis.title = element_text(size = 8, color = "#42376B"), axis.text = element_text(size = 8, color = "#42376B"), title = element_text(size = 8, color = "#42376B"), panel.border = element_rect(size = 1.5, color = "#42376B", fill = NA))
```

# Plain STATIS

```{r}
res.sts.byraters <- mpSTATIS(grand.tab, column.design = raters.coldx, statis.prepro.option = 'Plain_STATIS', DESIGN = raters, graph = FALSE)

# res.sts.byflavor <- mpSTATIS(grand.tab, column.design = flavors.coldx, statis.prepro.option = 'Plain_STATIS', DESIGN = flavors, graph = FALSE)

grand.tab.preproc <- res.sts.byraters$mexPosition.Data$Overview$preprocess.data

```

## RV scree plot

```{r}
eigres.sts <- data.frame(eig = res.sts.byraters$mexPosition.Data$InnerProduct$eigs, tau = res.sts.byraters$mexPosition.Data$InnerProduct$t)

#rv.sts.scree <- 
  PlotMyScree(eigres.sts, lwd = 0.8, cex = 1.3, title = "Scree plot for non-sparsed RV matrix from STATIS") + ggtheme
```


## Factor scores

```{r}
options(ggrepel.max.overlap = Inf)
sts.labels <- createxyLabels.gen(1,2,
                                 lambda = res.sts.byraters$mexPosition.Data$Table$eigs,
                                 tau = res.sts.byraters$mexPosition.Data$Table$t,
                                 axisName = "Component ")

## sts.constraints
sts.fi <- res.sts.byraters$mexPosition.Data$Table$fi
sts.pfi <- res.sts.byraters$mexPosition.Data$Table$partial.fi.array
colnames(sts.fi) <- colnames(sts.pfi) <- paste0("Dimension ", c(1:ncol(sts.fi)))
rownames(sts.pfi) <- rownames(sts.fi)
dimnames(sts.pfi)[[3]] <- unique(raters)
sts.constraints <- minmaxHelper4Partial(sts.fi, sts.pfi)

## Splus.U1
### Fi
Splus.fi <- createFactorMap(sts.fi,
                            constraints = sts.constraints,
                            text.cex = 2,
                            col.points = "#42376B",
                            col.labels = "#42376B",
                            col.background = NULL,
                            col.axes = "#42376B",
                            width.axes = 0.5,
                            label.axisName = "Component ",
                            alpha.axes = 0.5,
                            title = "STATIS: global and partial factor scores\nof products (rows)")
Splus.pfi <- createPartialFactorScoresMap(sts.fi,
                                          sts.pfi,
                                          colors4Blocks = col.raters$gc,
                                          colors4Items = "#42376B",
                                          alpha.lines = 0.7, alpha.points = 0.7, size.lines = 0.5)

Splus.fi$zeMap_background + Splus.pfi$mapColByBlocks + Splus.fi$zeMap_dots + Splus.fi$zeMap_text + sts.labels + ggtheme

### Fj
Splus.fj <- createFactorMap(res.sts.byraters$mexPosition.Data$Table$Q,
                            col.labels = col.flavors$oc,
                            col.points = col.flavors$oc,
                            text.cex = 2,
                            col.background = NULL,
                            col.axes = "#42376B",
                            width.axes = 0.5,
                            label.axisName = "Component ",
                            alpha.axes = 0.5,
                            title = "STATIS: column factor scores of \nraters and flavors (columns)")
Splus.fj$zeMap + sts.labels + ggtheme
```


## RV matrix

```{r}
RVmat <- res.sts.byraters$mexPosition.Data$InnerProduct$RVMatrix
rownames(RVmat) <- colnames(RVmat) <- unique(raters)
# pheatmap(res.sts.byraters$mexPosition.Data$InnerProduct$RVMatrix, clustering_method = 'ward.D2')

disRV2 <- dist(res.sts.byraters$mexPosition.Data$InnerProduct$fi[,c(1:2)])
pheatmap(RVmat, clustering_distance_rows = disRV2, clustering_distance_cols = disRV2, clustering_method = 'ward.D2')
hc <- hclust(disRV2, method = "ward.D2")
hc.3 <- cutree(hc, k = 3)

```

# sparse RV

```{r}
## Subspace 1
I.c <- nrow(RVmat)

rv.eig <- eigen(RVmat)

K <- 2L
U0 <- abs(rv.eig$vectors[, 1:K])
res.speig <- NULL
params <- seq(sqrt(I.c), 1, length = 25)

for (i in seq_along(params)) {
  cat(sprintf("Radius: %0.2f\n", params[i]))
  res.speig[[i]] <- tryCatch(
    sparseEIGEN(X = RVmat, k = K, init = U0, rds = rep(params[i], K)),
    error = function(e) NA)
  if (!is.na(res.speig[[i]])){
    U0 <- res.speig[[i]]$vectors
  }
}


res.speig.sparseindex <- lapply(res.speig, sparseIndexEigen, eigenValues = rv.eig$values)

si.mat.tmp <- sapply(res.speig.sparseindex, 
                     \(.) c(SI = .$SI[1], 
                            fitRatio = .$fitRatio[1],
                            zeroRatio = .$zeroRatio[1])) 
si.dat <- data.frame(
  radius = params,
  t(si.mat.tmp)
)

theta <- seq(pi, 3/2*pi, length.out = 150)
siplot1 <- ggplot(si.dat, aes(zeroRatio, fitRatio)) + 
  geom_hline(yintercept = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) + 
  geom_vline(xintercept = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) + 
  lapply(seq(0.25, 1.25, by = 0.25), function(r) annotate("path",
                                                          x = 1 + r*cos(theta),
                                                          y = 1 + r*sin(theta),
                                                          color = "darkorchid4")) + 
  lapply(seq(0.125, 1.5, by = 0.25), function(r) annotate("path",
                                                          x = 1 + r*cos(theta),
                                                          y = 1 + r*sin(theta),
                                                          color = "darkorchid4", size = 0.2))  +
  geom_abline(intercept = 0, slope = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) +
  geom_point(aes(size = SI)) + geom_line() +
  theme_bw() + scale_size_continuous(limits = 0:1) + 
  coord_equal(xlim=0:1, ylim = 0:1) + 
  labs(x = "Zero ratio", y = "Fit ratio", size = "Sparsity\nIndex") + 
  theme(
    panel.border = element_rect(size = 1.5, color = "#42376B", fill = NA),
    panel.grid = element_blank()) 

siplot1

rds.opt1 <- si.dat$radius[which.max(si.dat$SI)]

U0 <- abs(rv.eig$vectors[, 1:K])
rv.speig1 <- sparseEIGEN(X = RVmat, k = K, init = U0, rds = rep(rds.opt1, K))

## check
table(rv.speig1$vectors[,1] != 0, hc.3)

## Subspace 2
torem <- which(rv.speig1$vectors[, 1] != 0)
RVmat2 <- RVmat[-torem, -torem]
I.c2 <- nrow(RVmat2)
rv.eig2 <- eigen(RVmat2)

U0 <- abs(rv.eig2$vectors[, 1:K])
res.speig2 <- NULL
params2 <- seq(sqrt(I.c2), 1, length = 25)

for (i in seq_along(params2)) {
  cat(sprintf("Radius: %0.2f\n", params2[i]))
  res.speig2[[i]] <- tryCatch(
    sparseEIGEN(X = RVmat2, k = K, init = U0, rds = rep(params2[i], K)),
    error = function(e) NA)
  if (!is.na(res.speig2[[i]])){
    U0 <- res.speig2[[i]]$vectors
  }
}


res.speig.sparseindex2 <- lapply(res.speig2, sparseIndexEigen, eigenValues = rv.eig2$values)

si.mat.tmp2 <- sapply(res.speig.sparseindex2, 
                      \(.) c(SI = .$SI[1], 
                             fitRatio = .$fitRatio[1],
                             zeroRatio = .$zeroRatio[1])) 
si.dat2 <- data.frame(
  radius = params2,
  t(si.mat.tmp2)
)

siplot2 <- ggplot(si.dat2, aes(zeroRatio, fitRatio)) + 
  geom_hline(yintercept = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) + 
  geom_vline(xintercept = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) + 
  lapply(seq(0.25, 1.25, by = 0.25), function(r) annotate("path",
                                                          x = 1 + r*cos(theta),
                                                          y = 1 + r*sin(theta),
                                                          color = "darkorchid4")) + 
  lapply(seq(0.125, 1.5, by = 0.25), function(r) annotate("path",
                                                          x = 1 + r*cos(theta),
                                                          y = 1 + r*sin(theta),
                                                          color = "darkorchid4", size = 0.2))  +
  geom_abline(intercept = 0, slope = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) +
  geom_point(aes(size = SI)) + geom_line() +
  theme_bw() + scale_size_continuous(limits = 0:1) + 
  coord_equal(xlim=0:1, ylim = 0:1) + 
  labs(x = "Zero ratio", y = "Fit ratio", size = "Sparsity\nIndex") + 
  theme(
    panel.border = element_rect(size = 1.5, color = "#42376B", fill = NA),
    panel.grid = element_blank()) 

siplot2

rds.opt2 <- si.dat2$radius[which.max(si.dat2$SI)]

U0 <- abs(rv.eig2$vectors[, 1:K])
rv.speig2 <- sparseEIGEN(X = RVmat2, k = K, init = U0, rds = rep(rds.opt2, K))

## Third subspace
torem2 <- which(rv.speig2$vectors[, 1] != 0)
RVmat3 <- RVmat2[-torem2, -torem2]
rv.eig3 <- eigen(RVmat3)

## Organize
U1 <- rv.speig1$vectors[, 1]
U3 <- U2 <- rep(0, I.c)
U2[-torem] <- rv.speig2$vectors[, 1]
U3[-torem][-torem2] <- abs(rv.eig3$vectors[, 1])

Usp <- data.frame(U1 = U1, U2 = U2, U3 = U3)
rownames(Usp) <- unique(raters)

## check
class <- Usp %>% transmute(class = ifelse(U1 > 0, "U1", ifelse(U2 > 0, "U2", "U3")))
table(class$class, hc.3)
```

## lolliplops
```{r}
dat.U <- data.frame(
  ID = rownames(Usp),
  # IDnum = as.numeric(factor(rownames(Usp))),
  Usp, cluster = factor(hc.3))

dat.U4lol <- dat.U[hc$order,]
dat.U4lol$IDnum <- c(1:nrow(dat.U4lol))

lol1 <- ggplot(dat.U4lol, aes(IDnum, U1, color = cluster)) + 
  geom_point() + 
  geom_segment(aes(xend = IDnum, y = 0, yend = U1)) + 
  theme_minimal() + labs(x = "") + theme(axis.text.x = element_blank())

lol2 <- ggplot(dat.U4lol, aes(IDnum, U2, color = cluster)) + 
  geom_point() + 
  geom_segment(aes(xend = IDnum, y = 0, yend = U2)) + 
  theme_minimal()  + labs(x = "")+ theme(axis.text.x = element_blank())

lol3 <- ggplot(dat.U4lol, aes(IDnum, U3, color = cluster)) + 
  geom_point() + 
  geom_segment(aes(xend = IDnum, y = 0, yend = U3)) + 
  theme_minimal()  + labs(x = "")+ theme(axis.text.x = element_blank())

ggpubr::ggarrange(lol1, lol2, lol3, nrow = 3, common.legend = TRUE)

```

## Compromise

```{r}
## alpha
dat.alpha <- t(t(dat.U[, c("U1", "U2", "U3")])/colSums(dat.U[, c("U1", "U2", "U3")])) %>% as.data.frame
alpha.mat <- dat.alpha[raters,]

which1 <- alpha.mat$U1 != 0
which2 <- alpha.mat$U2 != 0
which3 <- alpha.mat$U3 != 0

## Compute Splus
#!! the columns are reordered
# Splus.U1 <- SPAFAC:::ComputeSplus(grand.tab.listbyflavor, 1/sqrt(dat.alpha$U1), isCube = FALSE)
# Splus.U2 <- SPAFAC:::ComputeSplus(grand.tab.listbyflavor, 1/sqrt(dat.alpha$U2), isCube = FALSE)
# Splus.U3 <- SPAFAC:::ComputeSplus(grand.tab.listbyflavor, 1/sqrt(dat.alpha$U3), isCube = FALSE)

Splus1.svd <- GSVD::gsvd(grand.tab.preproc[,which1], LW = rep(1/nrow(grand.tab), nrow(grand.tab)), RW = alpha.mat$U1[which1])
Splus2.svd <- GSVD::gsvd(grand.tab.preproc[,which2], LW = rep(1/nrow(grand.tab), nrow(grand.tab)), RW = alpha.mat$U2[which2])
Splus3.svd <- GSVD::gsvd(grand.tab.preproc[,which3], LW = rep(1/nrow(grand.tab), nrow(grand.tab)), RW = alpha.mat$U3[which3])

colnames(Splus1.svd$u) <- colnames(Splus1.svd$v) <- colnames(Splus1.svd$p) <- colnames(Splus1.svd$q) <- paste0("Dimension ", c(1:ncol(Splus1.svd$u)))
colnames(Splus2.svd$u) <- colnames(Splus2.svd$v) <- colnames(Splus2.svd$p) <- colnames(Splus2.svd$q) <- paste0("Dimension ", c(1:ncol(Splus2.svd$u)))
colnames(Splus3.svd$u) <- colnames(Splus3.svd$v) <- colnames(Splus3.svd$p) <- colnames(Splus3.svd$q) <- paste0("Dimension ", c(1:ncol(Splus3.svd$u)))

## organize output
#================= FUNC =================
STATIS.Sout <- function(dattab, svdres, M, alpha, design){
  out <- list(svd = list(u = svdres$u, v = svdres$v, d = svdres$d),
              gsvd = list(p = svdres$p, q = svdres$q, d = svdres$d, M = M, W = alpha),
              alpha = alpha,
              eig = svdres$l,
              tau = svdres$l/sum(svdres$l),
              fi = t(t(svdres$p) * svdres$d),
              fj = t(t(svdres$q) * svdres$d),
              partial.fi = array(dim = c(dim(svdres$u), length(unique(design)))))
  design.fac <- factor(design, unique(design))
  dattab.list <- split(as.data.frame(t(dattab)), design.fac) %>% lapply(t)
  dattab.vlist <- split(as.data.frame(svdres$q), design.fac) %>% lapply(as.matrix)
  out$partial.fi <- mapply("%*%", dattab.list, dattab.vlist) %>% array(dim = c(dim(svdres$u), length(unique(design))), 
                                                                       dimnames = list(rownames(svdres$u), 
                                                                                       colnames(svdres$u), 
                                                                                       unique(design)))
  out$svd.list$X <- dattab.list
  out$svd.list$v <- dattab.vlist
  return(out)
}
#========================================

# get factorized design
Splus1.res <- STATIS.Sout(grand.tab.preproc[,which1], Splus1.svd, rep(1/nrow(grand.tab), nrow(grand.tab)), alpha.mat$U1[which1], raters[which1])
Splus2.res <- STATIS.Sout(grand.tab.preproc[,which2], Splus2.svd, rep(1/nrow(grand.tab), nrow(grand.tab)), alpha.mat$U2[which2], raters[which2])
Splus3.res <- STATIS.Sout(grand.tab.preproc[,which3], Splus3.svd, rep(1/nrow(grand.tab), nrow(grand.tab)), alpha.mat$U3[which3], raters[which3])

##*** CHECK ***
##*SPAFAC:::ComputeSplus(Splus1.res$partial.fi, unique(alpha.mat$U1[which1]), isCube = TRUE)
##*Splus1.res$fi
```

### Figures - Splus from U1
```{r}
## Labels
stsU1.labels <- createxyLabels.gen(1,2,
                                   lambda = Splus1.res$eig,
                                   tau = Splus1.res$tau,
                                   axisName = "Component ")

stsU2.labels <- createxyLabels.gen(1,2,
                                   lambda = Splus2.res$eig,
                                   tau = Splus2.res$tau,
                                   axisName = "Component ")

stsU3.labels <- createxyLabels.gen(1,2,
                                   lambda = Splus3.res$eig,
                                   tau = Splus3.res$tau,
                                   axisName = "Component ")

## sts.constraints
stsU1.constraints <- minmaxHelper4Partial(Splus1.res$fi, Splus1.res$partial.fi)
stsU2.constraints <- minmaxHelper4Partial(Splus2.res$fi, Splus2.res$partial.fi)
stsU3.constraints <- minmaxHelper4Partial(Splus3.res$fi, Splus3.res$partial.fi)

## Splus.U1
### Fi
Splus1.fi <- createFactorMap(Splus1.res$fi,
                             constraints = stsU1.constraints,
                             text.cex = 2,
                             col.points = "#42376B",
                             col.labels = "#42376B",
                             col.background = NULL,
                             col.axes = "#42376B",
                             width.axes = 0.5,
                             label.axisName = "Component ",
                             alpha.axes = 0.5,
                             title = "STATIS: global and partial factor scores\nof products (rows)")
Splus1.pfi <- createPartialFactorScoresMap(Splus1.res$fi,
                                           Splus1.res$partial.fi,
                                           colors4Blocks = col.raters$gc[dimnames(Splus1.res$partial.fi)[3][[1]],],
                                           colors4Items = "#42376B",
                                           alpha.lines = 0.7, alpha.points = 0.7, size.lines = 0.5)

Splus1.fi$zeMap_background + Splus1.pfi$mapColByBlocks + Splus1.fi$zeMap_dots + Splus1.fi$zeMap_text + stsU1.labels + ggtheme

### Fj
Splus1.fj <- createFactorMap(Splus1.res$fj,
                             col.labels = col.flavors$oc[which1],
                             col.points = col.flavors$oc[which1],
                             text.cex = 2,
                             col.background = NULL,
                             col.axes = "#42376B",
                             width.axes = 0.5,
                             label.axisName = "Component ",
                             alpha.axes = 0.5,
                             title = "STATIS: column factor scores of \nraters and flavors (columns)")
Splus1.fj$zeMap + stsU1.labels + ggtheme

## Splus.U2 !!! WEIRD !!!
### Fi
Splus2.fi <- createFactorMap(Splus2.res$fi,
                             constraints = stsU2.constraints,
                             text.cex = 2,
                             col.points = "#42376B",
                             col.labels = "#42376B",
                             col.background = NULL,
                             col.axes = "#42376B",
                             width.axes = 0.5,
                             label.axisName = "Component ",
                             alpha.axes = 0.5,
                             title = "STATIS: global and partial factor scores\nof products (rows)")
Splus2.pfi <- createPartialFactorScoresMap(Splus2.res$fi,
                                           Splus2.res$partial.fi,
                                           colors4Blocks = col.raters$gc[dimnames(Splus2.res$partial.fi)[3][[1]],],
                                           colors4Items = "#42376B",
                                           alpha.lines = 0.7, alpha.points = 0.7, size.lines = 0.5)

Splus2.fi$zeMap_background + Splus2.pfi$mapColByBlocks + Splus2.fi$zeMap_dots + Splus2.fi$zeMap_text + stsU2.labels + ggtheme

### Fj
Splus2.fj <- createFactorMap(Splus2.res$fj,
                             col.labels = col.flavors$oc[which2],
                             col.points = col.flavors$oc[which2],
                             text.cex = 2,
                             col.background = NULL,
                             col.axes = "#42376B",
                             width.axes = 0.5,
                             label.axisName = "Component ",
                             alpha.axes = 0.5,
                             title = "STATIS: column factor scores of \nraters and flavors (columns)")
Splus2.fj$zeMap + stsU2.labels + ggtheme

## Splus.U3
### Fi
Splus3.fi <- createFactorMap(Splus3.res$fi,
                             constraints = stsU3.constraints,
                             text.cex = 2,
                             col.points = "#42376B",
                             col.labels = "#42376B",
                             col.background = NULL,
                             col.axes = "#42376B",
                             width.axes = 0.5,
                             label.axisName = "Component ",
                             alpha.axes = 0.5,
                             title = "STATIS: global and partial factor scores\nof products (rows)")
Splus3.pfi <- createPartialFactorScoresMap(Splus3.res$fi,
                                           Splus3.res$partial.fi,
                                           colors4Blocks = col.raters$gc[dimnames(Splus3.res$partial.fi)[3][[1]],],
                                           colors4Items = "#42376B",
                                           alpha.lines = 0.7, alpha.points = 0.7, size.lines = 0.5)

Splus3.fi$zeMap_background + Splus3.pfi$mapColByBlocks + Splus3.fi$zeMap_dots + Splus3.fi$zeMap_text + stsU3.labels + ggtheme

### Fj
Splus3.fj <- createFactorMap(Splus3.res$fj,
                             col.labels = col.flavors$oc[which3],
                             col.points = col.flavors$oc[which3],
                             text.cex = 2,
                             col.background = NULL,
                             col.axes = "#42376B",
                             width.axes = 0.5,
                             label.axisName = "Component ",
                             alpha.axes = 0.5,
                             title = "STATIS: column factor scores of \nraters and flavors (columns)")
Splus3.fj$zeMap + stsU3.labels + ggtheme
```

## Sparse compromise

```{r}
RV.ns.alpha <- res.sts.byraters$mexPosition.Data$InnerProduct$alphaWeights
names(RV.ns.alpha) <- sub(".","",names(RV.ns.alpha))
alpha.mat.cp <- recode(raters, !!!RV.ns.alpha)

# Sparsity index - by raters
### Run iterations
K <- 4L

I <- 8
J <- ncol(grand.tab)
J.raters <- length(unique(raters))

parz <- expand.grid(
  rdsleft = sqrt(I),#seq(sqrt(I), 1, length = 15),
  rdsright = seq(sqrt(J.raters), 1, length = 15))

parz <- parz[order(rowSums(parz^2/c(I,J.raters)), decreasing = T), ]

iter <- 1
res.ssts.list <- NULL
U0 <- NULL
V0 <- NULL

for (rds.iter in 1:nrow(parz)) {
  cat(sprintf("Left radius: %0.2f - Right radius: %0.2f\n", parz[rds.iter, 1], parz[rds.iter, 2]))
  res.ssts.list[[iter]] <- sparseGSVD(grand.tab.preproc, 
                                      LW = rep(1/nrow(grand.tab), nrow(grand.tab)), 
                                      RW = alpha.mat.cp,
                                      k = K,
                                      init = "svd", seed = 1000, 
                                      rdsLeft = rep(parz[rds.iter, 1], K), 
                                      rdsRight = rep(parz[rds.iter, 2], K),
                                      grpRight = raters.fac)
  # U0 <- res.ssts.list[[iter]]$p
  # V0 <- res.ssts.list[[iter]]$q
  iter <- iter + 1
}

### record results
dat.si.byraters <- data.frame(
  parz = parz, 
  SI = unname(t(data.frame(SI = sapply(res.ssts.list, extract_si, "SI", TRUE)))))

dat.si.m.byraters <- dat.si.byraters %>% tidyr::pivot_longer(starts_with("SI"), names_to = "k", names_prefix = "SI\\.")

dat.fit.zeros.byraters <- data.frame(
  rdsleft = dat.si.m.byraters$parz.rdsleft, 
  rdsright = dat.si.m.byraters$parz.rdsright, 
  k = dat.si.m.byraters$k,
  fit = pivot_the_tab(sapply(res.ssts.list, extract_si, "r1", TRUE)),
  zeros = pivot_the_tab(sapply(res.ssts.list, extract_si, "r4", TRUE)),
  SI = dat.si.m.byraters$value)

theta <- seq(pi, 3/2*pi, length.out = 150)
```

```{r fitzeroratioplot}
dimcol <- GetTolColors(n = 7, scheme = "discrete rainbow")
names(dimcol) <- as.factor(c(7:1))
# dimcol <- dimcol[c("2","3","4","5","6","7")]
dimcol["2"] <- "#f7c856"

dat.fit.zeros.byraters <- na.omit(dat.fit.zeros.byraters)
# dat.fit.zeros <- na.omit(dat.fit.zeros %>% filter(k %in% c("2", "3", "4", "5","6")))
dat.fit.zeros.byraters$max <- ifelse(dat.fit.zeros.byraters$k > 1 & dat.fit.zeros.byraters$SI == max(dat.fit.zeros.byraters$SI[which(dat.fit.zeros.byraters$k > 1)]), "MAX", "NOTMAX")
dat.fit.zeros.byraters$MAX <- ifelse(dat.fit.zeros.byraters$k > 1 & dat.fit.zeros.byraters$SI == max(dat.fit.zeros.byraters$SI[which(dat.fit.zeros.byraters$k > 1)]), "darkorchid4", "white")
dat.fit.zeros.byraters$alpha <- ifelse(dat.fit.zeros.byraters$k > 1 & dat.fit.zeros.byraters$SI == max(dat.fit.zeros.byraters$SI[which(dat.fit.zeros.byraters$k > 1)]), 1, 0.2)

siplot <- ggplot(dat.fit.zeros.byraters, aes(zeros, fit)) + 
  geom_hline(yintercept = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) + 
  geom_vline(xintercept = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) + 
  lapply(seq(0.25, 1.25, by = 0.25), function(r) annotate("path",
                                                          x = 1 + r*cos(theta),
                                                          y = 1 + r*sin(theta),
                                                          color = "darkorchid4")) + 
  lapply(seq(0.125, 1.5, by = 0.25), function(r) annotate("path",
                                                          x = 1 + r*cos(theta),
                                                          y = 1 + r*sin(theta),
                                                          color = "darkorchid4", size = 0.2))  +
  geom_abline(intercept = 0, slope = 1, color = "darkorchid4", alpha = 0.6, linetype = 3) +
  geom_point(aes(fill = k, alpha = I(alpha)), color = dat.fit.zeros.byraters$MAX, shape = 21, stroke = 1) +
  guides(color = guide_legend(override.aes = list(shape = 19, color = dimcol), nrow = 1, byrow = TRUE), shape = 19) +
  theme_bw() + 
  scale_color_manual(breaks= as.factor(c(1:7)), values = dimcol) +
  scale_fill_manual(breaks= as.factor(c(1:7)), values = dimcol) +
  coord_equal(xlim=0:1, ylim = 0:1) + 
  labs(x = "Zero ratio", y = "Fit", size = "Sparsity\nIndex", fill = "Number of\nComponents") + 
  # ggtitle("Ratio of zeros as a\nfunction of the fit ratio") + 
  theme(
    axis.title = element_text(size = 8, color = "#42376B"), 
    axis.text = element_text(size = 8, color = "#42376B"), 
    title = element_text(size = 8, color = "#42376B"),
    legend.key.size = unit(0.1, "cm"), legend.text = element_text(size = 6), legend.position = "right",
    legend.spacing.x = unit(0.05, "cm"),
    legend.margin = margin(0,0,0,0), legend.box.margin = margin(-5,0,0,0),
    legend.title.align = 0, legend.title = element_text(size = 6),
    panel.border = element_rect(size = 1.5, color = "#42376B", fill = NA),
    plot.margin = unit(c(0.1,0,0,0), unit = "cm"),
    panel.grid = element_blank()) + 
  with(dat.fit.zeros.byraters[dat.fit.zeros.byraters$max == "MAX",], annotate(geom = "point", x = zeros, y = fit, alpha = alpha, color = dimcol[k], size = 1)) +
  with(dat.fit.zeros.byraters[dat.fit.zeros.byraters$max == "MAX",], annotate(geom = "segment", x = zeros + 0.25, y = fit + 0.2, xend = zeros+ 0.02, yend = fit + 0.02, arrow = arrow(length = unit(0.05, "inches"), type = "closed"), color = "darkorchid4", size = 0.6)) + #0.05, 0.5
  with(dat.fit.zeros.byraters[dat.fit.zeros.byraters$max == "MAX",], annotate(geom = "segment", x = zeros + 0.025, y = fit + 0.022, xend = zeros+ 0.02, yend = fit + 0.02, arrow = arrow(length = unit(0.04, "inches"), type = "closed"), color = dimcol[k], size = 0.01)) + #0.04, 0.01
  with(dat.fit.zeros.byraters[dat.fit.zeros.byraters$max == "MAX",], annotate(geom = "label", x = zeros + 0.26, y = fit + 0.18, color = "darkorchid4", label = substring(sprintf("%.3f", SI), 2), fill = dimcol[k], size = 2.5))

siplot
```

## sSTATIS results
```{r}
optres <- dat.fit.zeros.byraters[dat.fit.zeros.byraters$max == "MAX",]
kopt <- optres$k
rdsleftopt <- optres$rdsleft
rdsrightopt <- optres$rdsright
SIopt <- optres$SI

kopt;rdsleftopt/sqrt(I);rdsrightopt/sqrt(J);SIopt
```

```{r}
## run opt sparseSTATIS
ssts.svd<- sparseGSVD(grand.tab.preproc, 
                      LW = rep(1/nrow(grand.tab), nrow(grand.tab)), 
                      RW = alpha.mat.cp,
                      k = kopt,
                      init = "svd", seed = 1000, 
                      rdsLeft = rep(rdsleftopt, kopt), 
                      rdsRight = rep(rdsrightopt, kopt),
                      grpRight = raters.fac)
colnames(ssts.svd$u) <- colnames(ssts.svd$v) <- colnames(ssts.svd$p) <- colnames(ssts.svd$q) <- paste0("Dimension ", c(1:ncol(ssts.svd$u)))
ssts.res <- STATIS.Sout(grand.tab.preproc, ssts.svd, rep(1/nrow(grand.tab), nrow(grand.tab)), alpha.mat.cp, raters.fac)
```

### Factor scores
```{r}
ssts.labels <- createxyLabels.gen(1,2,
                                  lambda = ssts.res$eig,
                                  tau = ssts.res$tau,
                                  axisName = "Component ")

## sts.constraints
ssts.constraints <- minmaxHelper4Partial(ssts.res$fi, ssts.res$partial.fi)

### Fi
ssts.fi <- createFactorMap(ssts.res$fi,
                           constraints = ssts.constraints,
                           text.cex = 2,
                           col.points = "#42376B",
                           col.labels = "#42376B",
                           col.background = NULL,
                           col.axes = "#42376B",
                           width.axes = 0.5,
                           label.axisName = "Component ",
                           alpha.axes = 0.5,
                           title = "sSTATIS: global and partial factor scores\nof products (rows)")
ssts.pfi <- createPartialFactorScoresMap(ssts.res$fi,
                                         ssts.res$partial.fi,
                                         colors4Blocks = col.raters$gc[dimnames(ssts.res$partial.fi)[3][[1]],],
                                         colors4Items = "#42376B",
                                         alpha.lines = 0.7, alpha.points = 0.7, size.lines = 0.5)

ssts.fi$zeMap_background + ssts.pfi$mapColByBlocks + ssts.fi$zeMap_dots + ssts.fi$zeMap_text + ssts.labels + ggtheme

### Fj
ssts.fj <- createFactorMap(ssts.res$fj,
                           col.labels = col.flavors$oc,
                           col.points = col.flavors$oc,
                           text.cex = 2,
                           col.background = NULL,
                           col.axes = "#42376B",
                           width.axes = 0.5,
                           label.axisName = "Component ",
                           alpha.axes = 0.5,
                           title = "sSTATIS: column factor scores of \nraters and flavors (columns)")
ssts.fj$zeMap + ssts.labels + ggtheme
```

